name: "compare_transcriptomes"
description: "Compara transcriptomas e remove proteínas codificantes baseado em códigos de classe"
keywords:
  - transcriptome
  - comparison
  - gtf
  - annotation
  - filtering
tools:
  - "r-base":
      description: "R statistical computing environment"
      homepage: "https://www.r-project.org/"
      documentation: "https://www.r-project.org/"
  - "tidyverse":
      description: "Collection of R packages for data science"
      homepage: "https://www.tidyverse.org/"
      documentation: "https://www.tidyverse.org/"
  - "rtracklayer":
      description: "R interface to genome annotation files"
      homepage: "https://bioconductor.org/packages/rtracklayer/"
      documentation: "https://bioconductor.org/packages/rtracklayer/"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - tmap_file:
      type: file
      description: "Arquivo TMAP do StringTie compare (.tmap)"
      pattern: "*.tmap"
  - refmap_file:
      type: file
      description: "Arquivo REFMAP do StringTie compare (.refmap)"
      pattern: "*.refmap"
  - annotated_gtf:
      type: file
      description: "Arquivo GTF anotado"
      pattern: "*.gtf"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - filtered_gtf:
      type: file
      description: "GTF filtrado sem proteínas codificantes"
      pattern: "*.remove_prot.gtf"
  - log:
      type: file
      description: "Arquivo de log da análise"
      pattern: "*.log"
  - versions:
      type: file
      description: "File containing software versions"
      pattern: "versions.yml"

authors:
  - "@gleisonm"
