name: "cpc2"
description: "Avalia o potencial codificante de proteínas em sequências de transcritos"
keywords:
  - coding potential
  - protein coding
  - lncrna
  - transcripts
  - classification
tools:
  - "cpc2":
      description: "Coding Potential Calculator 2: a fast and accurate coding potential assessment tool using sequence intrinsic features"
      homepage: "http://cpc2.gao-lab.org/"
      documentation: "http://cpc2.gao-lab.org/help.php"
      tool_dev_url: "https://github.com/gao-lab/CPC2_standalone"
      doi: "10.1093/nar/gkx428"
      licence: "GPL-3.0"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - fasta_file:
      type: file
      description: "Arquivo FASTA contendo sequências de transcritos"
      pattern: "*.{fa,fasta,fna}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - cpc2_results:
      type: file
      description: "Arquivo de resultados do CPC2 com classificação de potencial codificante"
      pattern: "*.txt"
  - log:
      type: file
      description: "Arquivo de log do processo"
      pattern: "*.log"
  - versions:
      type: file
      description: "File containing software versions"
      pattern: "versions.yml"

authors:
  - "@gleisonm"